// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flwcsnpgurcbyugssmvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsd2NzbnBndXJjYnl1Z3NzbXZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NDg0MzcsImV4cCI6MjA3MDAyNDQzN30.tMqmA_X5Rz5ttG7PUm6330thE8wLf9kpmMoJ9ZWd5kc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});